// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package sqlc

import (
	"context"
)

const countActiveMedicationCourses = `-- name: CountActiveMedicationCourses :one
SELECT COUNT(*) AS count
FROM health_medication_course
WHERE deleted_at IS NULL
  AND (end_date IS NULL OR end_date >= ?1)
`

func (q *Queries) CountActiveMedicationCourses(ctx context.Context, today *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveMedicationCourses, today)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBloodPressureEntry = `-- name: CreateBloodPressureEntry :one
INSERT INTO health_blood_pressure_entry (
  recorded_at,
  systolic,
  diastolic,
  pulse,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9
)
RETURNING
  id,
  recorded_at,
  systolic,
  diastolic,
  pulse,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type CreateBloodPressureEntryParams struct {
	RecordedAt       string
	Systolic         int64
	Diastolic        int64
	Pulse            *int64
	Note             *string
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
}

type CreateBloodPressureEntryRow struct {
	ID               int64
	RecordedAt       string
	Systolic         int64
	Diastolic        int64
	Pulse            *int64
	Note             *string
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
}

func (q *Queries) CreateBloodPressureEntry(ctx context.Context, arg CreateBloodPressureEntryParams) (CreateBloodPressureEntryRow, error) {
	row := q.db.QueryRowContext(ctx, createBloodPressureEntry,
		arg.RecordedAt,
		arg.Systolic,
		arg.Diastolic,
		arg.Pulse,
		arg.Note,
		arg.Source,
		arg.SourceRecordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateBloodPressureEntryRow
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Systolic,
		&i.Diastolic,
		&i.Pulse,
		&i.Note,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createBodyCompositionEntry = `-- name: CreateBodyCompositionEntry :one
INSERT INTO health_body_composition_entry (
  recorded_at,
  body_fat_percent,
  weight_value,
  weight_unit,
  method,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10
)
RETURNING
  id,
  recorded_at,
  body_fat_percent,
  weight_value,
  weight_unit,
  method,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type CreateBodyCompositionEntryParams struct {
	RecordedAt       string
	BodyFatPercent   *float64
	WeightValue      *float64
	WeightUnit       *string
	Method           *string
	Note             *string
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateBodyCompositionEntry(ctx context.Context, arg CreateBodyCompositionEntryParams) (HealthBodyCompositionEntry, error) {
	row := q.db.QueryRowContext(ctx, createBodyCompositionEntry,
		arg.RecordedAt,
		arg.BodyFatPercent,
		arg.WeightValue,
		arg.WeightUnit,
		arg.Method,
		arg.Note,
		arg.Source,
		arg.SourceRecordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i HealthBodyCompositionEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.BodyFatPercent,
		&i.WeightValue,
		&i.WeightUnit,
		&i.Method,
		&i.Note,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createImagingRecord = `-- name: CreateImagingRecord :one
INSERT INTO health_imaging_record (
  performed_at,
  modality,
  body_site,
  title,
  summary,
  impression,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9,
  ?10,
  ?11
)
RETURNING
  id,
  performed_at,
  modality,
  body_site,
  title,
  summary,
  impression,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type CreateImagingRecordParams struct {
	PerformedAt      string
	Modality         string
	BodySite         *string
	Title            *string
	Summary          string
	Impression       *string
	Note             *string
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateImagingRecord(ctx context.Context, arg CreateImagingRecordParams) (HealthImagingRecord, error) {
	row := q.db.QueryRowContext(ctx, createImagingRecord,
		arg.PerformedAt,
		arg.Modality,
		arg.BodySite,
		arg.Title,
		arg.Summary,
		arg.Impression,
		arg.Note,
		arg.Source,
		arg.SourceRecordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i HealthImagingRecord
	err := row.Scan(
		&i.ID,
		&i.PerformedAt,
		&i.Modality,
		&i.BodySite,
		&i.Title,
		&i.Summary,
		&i.Impression,
		&i.Note,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createImagingRecordNote = `-- name: CreateImagingRecordNote :one
INSERT INTO health_imaging_record_note (
  imaging_record_id,
  note_text,
  display_order
) VALUES (
  ?1,
  ?2,
  ?3
)
RETURNING
  id,
  imaging_record_id,
  note_text,
  display_order
`

type CreateImagingRecordNoteParams struct {
	ImagingRecordID int64
	NoteText        string
	DisplayOrder    int64
}

func (q *Queries) CreateImagingRecordNote(ctx context.Context, arg CreateImagingRecordNoteParams) (HealthImagingRecordNote, error) {
	row := q.db.QueryRowContext(ctx, createImagingRecordNote, arg.ImagingRecordID, arg.NoteText, arg.DisplayOrder)
	var i HealthImagingRecordNote
	err := row.Scan(
		&i.ID,
		&i.ImagingRecordID,
		&i.NoteText,
		&i.DisplayOrder,
	)
	return i, err
}

const createLabCollection = `-- name: CreateLabCollection :one
INSERT INTO health_lab_collection (
  collected_at,
  note,
  source,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5
)
RETURNING
  id,
  collected_at,
  note,
  source,
  created_at,
  updated_at,
  deleted_at
`

type CreateLabCollectionParams struct {
	CollectedAt string
	Note        *string
	Source      string
	CreatedAt   string
	UpdatedAt   *string
}

type CreateLabCollectionRow struct {
	ID          int64
	CollectedAt string
	Note        *string
	Source      string
	CreatedAt   string
	UpdatedAt   *string
	DeletedAt   *string
}

func (q *Queries) CreateLabCollection(ctx context.Context, arg CreateLabCollectionParams) (CreateLabCollectionRow, error) {
	row := q.db.QueryRowContext(ctx, createLabCollection,
		arg.CollectedAt,
		arg.Note,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateLabCollectionRow
	err := row.Scan(
		&i.ID,
		&i.CollectedAt,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLabPanel = `-- name: CreateLabPanel :one
INSERT INTO health_lab_panel (
  collection_id,
  panel_name,
  display_order
) VALUES (
  ?1,
  ?2,
  ?3
)
RETURNING
  id,
  collection_id,
  panel_name,
  display_order
`

type CreateLabPanelParams struct {
	CollectionID int64
	PanelName    string
	DisplayOrder int64
}

func (q *Queries) CreateLabPanel(ctx context.Context, arg CreateLabPanelParams) (HealthLabPanel, error) {
	row := q.db.QueryRowContext(ctx, createLabPanel, arg.CollectionID, arg.PanelName, arg.DisplayOrder)
	var i HealthLabPanel
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.PanelName,
		&i.DisplayOrder,
	)
	return i, err
}

const createLabResult = `-- name: CreateLabResult :one
INSERT INTO health_lab_result (
  panel_id,
  test_name,
  canonical_slug,
  value_text,
  value_numeric,
  units,
  range_text,
  flag,
  display_order
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9
)
RETURNING
  id,
  panel_id,
  test_name,
  canonical_slug,
  value_text,
  value_numeric,
  units,
  range_text,
  flag,
  display_order
`

type CreateLabResultParams struct {
	PanelID       int64
	TestName      string
	CanonicalSlug *string
	ValueText     string
	ValueNumeric  *float64
	Units         *string
	RangeText     *string
	Flag          *string
	DisplayOrder  int64
}

func (q *Queries) CreateLabResult(ctx context.Context, arg CreateLabResultParams) (HealthLabResult, error) {
	row := q.db.QueryRowContext(ctx, createLabResult,
		arg.PanelID,
		arg.TestName,
		arg.CanonicalSlug,
		arg.ValueText,
		arg.ValueNumeric,
		arg.Units,
		arg.RangeText,
		arg.Flag,
		arg.DisplayOrder,
	)
	var i HealthLabResult
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.TestName,
		&i.CanonicalSlug,
		&i.ValueText,
		&i.ValueNumeric,
		&i.Units,
		&i.RangeText,
		&i.Flag,
		&i.DisplayOrder,
	)
	return i, err
}

const createLabResultNote = `-- name: CreateLabResultNote :one
INSERT INTO health_lab_result_note (
  lab_result_id,
  note_text,
  display_order
) VALUES (
  ?1,
  ?2,
  ?3
)
RETURNING
  id,
  lab_result_id,
  note_text,
  display_order
`

type CreateLabResultNoteParams struct {
	LabResultID  int64
	NoteText     string
	DisplayOrder int64
}

func (q *Queries) CreateLabResultNote(ctx context.Context, arg CreateLabResultNoteParams) (HealthLabResultNote, error) {
	row := q.db.QueryRowContext(ctx, createLabResultNote, arg.LabResultID, arg.NoteText, arg.DisplayOrder)
	var i HealthLabResultNote
	err := row.Scan(
		&i.ID,
		&i.LabResultID,
		&i.NoteText,
		&i.DisplayOrder,
	)
	return i, err
}

const createMedicationCourse = `-- name: CreateMedicationCourse :one
INSERT INTO health_medication_course (
  name,
  dosage_text,
  start_date,
  end_date,
  note,
  source,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING
  id,
  name,
  dosage_text,
  start_date,
  end_date,
  note,
  source,
  created_at,
  updated_at,
  deleted_at
`

type CreateMedicationCourseParams struct {
	Name       string
	DosageText *string
	StartDate  string
	EndDate    *string
	Note       *string
	Source     string
	CreatedAt  string
	UpdatedAt  string
}

type CreateMedicationCourseRow struct {
	ID         int64
	Name       string
	DosageText *string
	StartDate  string
	EndDate    *string
	Note       *string
	Source     string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  *string
}

func (q *Queries) CreateMedicationCourse(ctx context.Context, arg CreateMedicationCourseParams) (CreateMedicationCourseRow, error) {
	row := q.db.QueryRowContext(ctx, createMedicationCourse,
		arg.Name,
		arg.DosageText,
		arg.StartDate,
		arg.EndDate,
		arg.Note,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateMedicationCourseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DosageText,
		&i.StartDate,
		&i.EndDate,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSleepEntry = `-- name: CreateSleepEntry :one
INSERT INTO health_sleep_entry (
  recorded_at,
  quality_score,
  wakeup_count,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING
  id,
  recorded_at,
  quality_score,
  wakeup_count,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type CreateSleepEntryParams struct {
	RecordedAt       string
	QualityScore     int64
	WakeupCount      *int64
	Note             *string
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateSleepEntry(ctx context.Context, arg CreateSleepEntryParams) (HealthSleepEntry, error) {
	row := q.db.QueryRowContext(ctx, createSleepEntry,
		arg.RecordedAt,
		arg.QualityScore,
		arg.WakeupCount,
		arg.Note,
		arg.Source,
		arg.SourceRecordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i HealthSleepEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.QualityScore,
		&i.WakeupCount,
		&i.Note,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWeightEntry = `-- name: CreateWeightEntry :one
INSERT INTO health_weight_entry (
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING
  id,
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at,
  deleted_at
`

type CreateWeightEntryParams struct {
	RecordedAt       string
	Value            float64
	Unit             string
	Source           string
	SourceRecordHash string
	Note             *string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateWeightEntry(ctx context.Context, arg CreateWeightEntryParams) (HealthWeightEntry, error) {
	row := q.db.QueryRowContext(ctx, createWeightEntry,
		arg.RecordedAt,
		arg.Value,
		arg.Unit,
		arg.Source,
		arg.SourceRecordHash,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i HealthWeightEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Value,
		&i.Unit,
		&i.Source,
		&i.SourceRecordHash,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBloodPressureEntry = `-- name: DeleteBloodPressureEntry :one
UPDATE health_blood_pressure_entry
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteBloodPressureEntryParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) DeleteBloodPressureEntry(ctx context.Context, arg DeleteBloodPressureEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteBloodPressureEntry, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteBodyCompositionEntry = `-- name: DeleteBodyCompositionEntry :one
UPDATE health_body_composition_entry
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteBodyCompositionEntryParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) DeleteBodyCompositionEntry(ctx context.Context, arg DeleteBodyCompositionEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteBodyCompositionEntry, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteImagingRecord = `-- name: DeleteImagingRecord :one
UPDATE health_imaging_record
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteImagingRecordParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) DeleteImagingRecord(ctx context.Context, arg DeleteImagingRecordParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteImagingRecord, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteImagingRecordNotesByRecord = `-- name: DeleteImagingRecordNotesByRecord :exec
DELETE FROM health_imaging_record_note
WHERE imaging_record_id = ?1
`

func (q *Queries) DeleteImagingRecordNotesByRecord(ctx context.Context, imagingRecordID int64) error {
	_, err := q.db.ExecContext(ctx, deleteImagingRecordNotesByRecord, imagingRecordID)
	return err
}

const deleteLabCollection = `-- name: DeleteLabCollection :one
UPDATE health_lab_collection
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteLabCollectionParams struct {
	DeletedAt *string
	UpdatedAt *string
	ID        int64
}

func (q *Queries) DeleteLabCollection(ctx context.Context, arg DeleteLabCollectionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteLabCollection, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteLabPanelsByCollection = `-- name: DeleteLabPanelsByCollection :exec
DELETE FROM health_lab_panel
WHERE collection_id = ?1
`

func (q *Queries) DeleteLabPanelsByCollection(ctx context.Context, collectionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLabPanelsByCollection, collectionID)
	return err
}

const deleteMedicationCourse = `-- name: DeleteMedicationCourse :one
UPDATE health_medication_course
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteMedicationCourseParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) DeleteMedicationCourse(ctx context.Context, arg DeleteMedicationCourseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteMedicationCourse, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteSleepEntry = `-- name: DeleteSleepEntry :one
UPDATE health_sleep_entry
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteSleepEntryParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) DeleteSleepEntry(ctx context.Context, arg DeleteSleepEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteSleepEntry, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteWeightEntry = `-- name: DeleteWeightEntry :one
UPDATE health_weight_entry
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteWeightEntryParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) DeleteWeightEntry(ctx context.Context, arg DeleteWeightEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteWeightEntry, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findManualSleepEntry = `-- name: FindManualSleepEntry :one
SELECT
  id,
  recorded_at,
  quality_score,
  wakeup_count,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
FROM health_sleep_entry
WHERE deleted_at IS NULL
  AND source = 'manual'
  AND substr(recorded_at, 1, 10) = ?1
ORDER BY id DESC
LIMIT 1
`

func (q *Queries) FindManualSleepEntry(ctx context.Context, recordedDate string) (HealthSleepEntry, error) {
	row := q.db.QueryRowContext(ctx, findManualSleepEntry, recordedDate)
	var i HealthSleepEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.QualityScore,
		&i.WakeupCount,
		&i.Note,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findManualWeightEntry = `-- name: FindManualWeightEntry :one
SELECT
  id,
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at,
  deleted_at
FROM health_weight_entry
WHERE deleted_at IS NULL
  AND source = 'manual'
  AND substr(recorded_at, 1, 10) = ?1
  AND unit = ?2
ORDER BY id DESC
LIMIT 1
`

type FindManualWeightEntryParams struct {
	RecordedDate string
	Unit         string
}

func (q *Queries) FindManualWeightEntry(ctx context.Context, arg FindManualWeightEntryParams) (HealthWeightEntry, error) {
	row := q.db.QueryRowContext(ctx, findManualWeightEntry, arg.RecordedDate, arg.Unit)
	var i HealthWeightEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Value,
		&i.Unit,
		&i.Source,
		&i.SourceRecordHash,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLabCollection = `-- name: GetLabCollection :one
SELECT
  id,
  collected_at,
  note,
  source,
  created_at,
  updated_at,
  deleted_at
FROM health_lab_collection
WHERE id = ?1
  AND deleted_at IS NULL
`

type GetLabCollectionRow struct {
	ID          int64
	CollectedAt string
	Note        *string
	Source      string
	CreatedAt   string
	UpdatedAt   *string
	DeletedAt   *string
}

func (q *Queries) GetLabCollection(ctx context.Context, id int64) (GetLabCollectionRow, error) {
	row := q.db.QueryRowContext(ctx, getLabCollection, id)
	var i GetLabCollectionRow
	err := row.Scan(
		&i.ID,
		&i.CollectedAt,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveMedicationCourses = `-- name: ListActiveMedicationCourses :many
SELECT
  id,
  name,
  dosage_text,
  start_date,
  end_date,
  note,
  source,
  created_at,
  updated_at,
  deleted_at
FROM health_medication_course
WHERE deleted_at IS NULL
  AND (end_date IS NULL OR end_date >= ?1)
ORDER BY start_date DESC, id DESC
`

type ListActiveMedicationCoursesRow struct {
	ID         int64
	Name       string
	DosageText *string
	StartDate  string
	EndDate    *string
	Note       *string
	Source     string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  *string
}

func (q *Queries) ListActiveMedicationCourses(ctx context.Context, today *string) ([]ListActiveMedicationCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMedicationCourses, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveMedicationCoursesRow
	for rows.Next() {
		var i ListActiveMedicationCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DosageText,
			&i.StartDate,
			&i.EndDate,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBloodPressureEntries = `-- name: ListBloodPressureEntries :many
SELECT
  id,
  recorded_at,
  systolic,
  diastolic,
  pulse,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
FROM health_blood_pressure_entry
WHERE deleted_at IS NULL
  AND (?1 IS NULL OR recorded_at >= ?1)
  AND (?2 IS NULL OR recorded_at <= ?2)
ORDER BY recorded_at DESC, id DESC
LIMIT CASE
  WHEN ?3 IS NULL THEN -1
  ELSE ?3
END
`

type ListBloodPressureEntriesParams struct {
	FromRecordedAt interface{}
	ToRecordedAt   interface{}
	LimitCount     interface{}
}

type ListBloodPressureEntriesRow struct {
	ID               int64
	RecordedAt       string
	Systolic         int64
	Diastolic        int64
	Pulse            *int64
	Note             *string
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
}

func (q *Queries) ListBloodPressureEntries(ctx context.Context, arg ListBloodPressureEntriesParams) ([]ListBloodPressureEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listBloodPressureEntries, arg.FromRecordedAt, arg.ToRecordedAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBloodPressureEntriesRow
	for rows.Next() {
		var i ListBloodPressureEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.Systolic,
			&i.Diastolic,
			&i.Pulse,
			&i.Note,
			&i.Source,
			&i.SourceRecordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBodyCompositionEntries = `-- name: ListBodyCompositionEntries :many
SELECT
  id,
  recorded_at,
  body_fat_percent,
  weight_value,
  weight_unit,
  method,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
FROM health_body_composition_entry
WHERE deleted_at IS NULL
  AND (?1 IS NULL OR recorded_at >= ?1)
  AND (?2 IS NULL OR recorded_at <= ?2)
ORDER BY recorded_at DESC, id DESC
LIMIT CASE
  WHEN ?3 IS NULL THEN -1
  ELSE ?3
END
`

type ListBodyCompositionEntriesParams struct {
	FromRecordedAt interface{}
	ToRecordedAt   interface{}
	LimitCount     interface{}
}

func (q *Queries) ListBodyCompositionEntries(ctx context.Context, arg ListBodyCompositionEntriesParams) ([]HealthBodyCompositionEntry, error) {
	rows, err := q.db.QueryContext(ctx, listBodyCompositionEntries, arg.FromRecordedAt, arg.ToRecordedAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthBodyCompositionEntry
	for rows.Next() {
		var i HealthBodyCompositionEntry
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.BodyFatPercent,
			&i.WeightValue,
			&i.WeightUnit,
			&i.Method,
			&i.Note,
			&i.Source,
			&i.SourceRecordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagingRecordNotes = `-- name: ListImagingRecordNotes :many
SELECT
  id,
  imaging_record_id,
  note_text,
  display_order
FROM health_imaging_record_note
ORDER BY imaging_record_id ASC, display_order ASC, id ASC
`

func (q *Queries) ListImagingRecordNotes(ctx context.Context) ([]HealthImagingRecordNote, error) {
	rows, err := q.db.QueryContext(ctx, listImagingRecordNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthImagingRecordNote
	for rows.Next() {
		var i HealthImagingRecordNote
		if err := rows.Scan(
			&i.ID,
			&i.ImagingRecordID,
			&i.NoteText,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagingRecords = `-- name: ListImagingRecords :many
SELECT
  id,
  performed_at,
  modality,
  body_site,
  title,
  summary,
  impression,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
FROM health_imaging_record
WHERE deleted_at IS NULL
  AND (?1 IS NULL OR performed_at >= ?1)
  AND (?2 IS NULL OR performed_at <= ?2)
  AND (?3 IS NULL OR lower(modality) = lower(?3))
  AND (?4 IS NULL OR (body_site IS NOT NULL AND lower(body_site) = lower(?4)))
ORDER BY performed_at DESC, id DESC
LIMIT CASE
  WHEN ?5 IS NULL THEN -1
  ELSE ?5
END
`

type ListImagingRecordsParams struct {
	FromPerformedAt interface{}
	ToPerformedAt   interface{}
	Modality        interface{}
	BodySite        interface{}
	LimitCount      interface{}
}

func (q *Queries) ListImagingRecords(ctx context.Context, arg ListImagingRecordsParams) ([]HealthImagingRecord, error) {
	rows, err := q.db.QueryContext(ctx, listImagingRecords,
		arg.FromPerformedAt,
		arg.ToPerformedAt,
		arg.Modality,
		arg.BodySite,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthImagingRecord
	for rows.Next() {
		var i HealthImagingRecord
		if err := rows.Scan(
			&i.ID,
			&i.PerformedAt,
			&i.Modality,
			&i.BodySite,
			&i.Title,
			&i.Summary,
			&i.Impression,
			&i.Note,
			&i.Source,
			&i.SourceRecordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabCollections = `-- name: ListLabCollections :many
SELECT
  id,
  collected_at,
  note,
  source,
  created_at,
  updated_at,
  deleted_at
FROM health_lab_collection
WHERE deleted_at IS NULL
ORDER BY collected_at DESC, id DESC
`

type ListLabCollectionsRow struct {
	ID          int64
	CollectedAt string
	Note        *string
	Source      string
	CreatedAt   string
	UpdatedAt   *string
	DeletedAt   *string
}

func (q *Queries) ListLabCollections(ctx context.Context) ([]ListLabCollectionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLabCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabCollectionsRow
	for rows.Next() {
		var i ListLabCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CollectedAt,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabPanels = `-- name: ListLabPanels :many
SELECT
  id,
  collection_id,
  panel_name,
  display_order
FROM health_lab_panel
ORDER BY collection_id ASC, display_order ASC, id ASC
`

func (q *Queries) ListLabPanels(ctx context.Context) ([]HealthLabPanel, error) {
	rows, err := q.db.QueryContext(ctx, listLabPanels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthLabPanel
	for rows.Next() {
		var i HealthLabPanel
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.PanelName,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabResultNotes = `-- name: ListLabResultNotes :many
SELECT
  id,
  lab_result_id,
  note_text,
  display_order
FROM health_lab_result_note
ORDER BY lab_result_id ASC, display_order ASC, id ASC
`

func (q *Queries) ListLabResultNotes(ctx context.Context) ([]HealthLabResultNote, error) {
	rows, err := q.db.QueryContext(ctx, listLabResultNotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthLabResultNote
	for rows.Next() {
		var i HealthLabResultNote
		if err := rows.Scan(
			&i.ID,
			&i.LabResultID,
			&i.NoteText,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabResults = `-- name: ListLabResults :many
SELECT
  id,
  panel_id,
  test_name,
  canonical_slug,
  value_text,
  value_numeric,
  units,
  range_text,
  flag,
  display_order
FROM health_lab_result
ORDER BY panel_id ASC, display_order ASC, id ASC
`

func (q *Queries) ListLabResults(ctx context.Context) ([]HealthLabResult, error) {
	rows, err := q.db.QueryContext(ctx, listLabResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthLabResult
	for rows.Next() {
		var i HealthLabResult
		if err := rows.Scan(
			&i.ID,
			&i.PanelID,
			&i.TestName,
			&i.CanonicalSlug,
			&i.ValueText,
			&i.ValueNumeric,
			&i.Units,
			&i.RangeText,
			&i.Flag,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabResultsWithCollection = `-- name: ListLabResultsWithCollection :many
SELECT
  health_lab_result.id,
  health_lab_result.panel_id,
  health_lab_result.test_name,
  health_lab_result.canonical_slug,
  health_lab_result.value_text,
  health_lab_result.value_numeric,
  health_lab_result.units,
  health_lab_result.range_text,
  health_lab_result.flag,
  health_lab_result.display_order,
  health_lab_collection.collected_at,
  health_lab_collection.id AS collection_id,
  health_lab_panel.panel_name
FROM health_lab_result
INNER JOIN health_lab_panel ON health_lab_panel.id = health_lab_result.panel_id
INNER JOIN health_lab_collection ON health_lab_collection.id = health_lab_panel.collection_id
WHERE health_lab_result.canonical_slug IS NOT NULL
  AND health_lab_collection.deleted_at IS NULL
ORDER BY health_lab_collection.collected_at DESC, health_lab_result.id DESC
`

type ListLabResultsWithCollectionRow struct {
	ID            int64
	PanelID       int64
	TestName      string
	CanonicalSlug *string
	ValueText     string
	ValueNumeric  *float64
	Units         *string
	RangeText     *string
	Flag          *string
	DisplayOrder  int64
	CollectedAt   string
	CollectionID  int64
	PanelName     string
}

func (q *Queries) ListLabResultsWithCollection(ctx context.Context) ([]ListLabResultsWithCollectionRow, error) {
	rows, err := q.db.QueryContext(ctx, listLabResultsWithCollection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabResultsWithCollectionRow
	for rows.Next() {
		var i ListLabResultsWithCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.PanelID,
			&i.TestName,
			&i.CanonicalSlug,
			&i.ValueText,
			&i.ValueNumeric,
			&i.Units,
			&i.RangeText,
			&i.Flag,
			&i.DisplayOrder,
			&i.CollectedAt,
			&i.CollectionID,
			&i.PanelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationCourses = `-- name: ListMedicationCourses :many
SELECT
  id,
  name,
  dosage_text,
  start_date,
  end_date,
  note,
  source,
  created_at,
  updated_at,
  deleted_at
FROM health_medication_course
WHERE deleted_at IS NULL
ORDER BY start_date DESC, id DESC
`

type ListMedicationCoursesRow struct {
	ID         int64
	Name       string
	DosageText *string
	StartDate  string
	EndDate    *string
	Note       *string
	Source     string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  *string
}

func (q *Queries) ListMedicationCourses(ctx context.Context) ([]ListMedicationCoursesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMedicationCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMedicationCoursesRow
	for rows.Next() {
		var i ListMedicationCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DosageText,
			&i.StartDate,
			&i.EndDate,
			&i.Note,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSleepEntries = `-- name: ListSleepEntries :many
SELECT
  id,
  recorded_at,
  quality_score,
  wakeup_count,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
FROM health_sleep_entry
WHERE deleted_at IS NULL
  AND (?1 IS NULL OR recorded_at >= ?1)
  AND (?2 IS NULL OR recorded_at <= ?2)
ORDER BY recorded_at DESC, id DESC
LIMIT CASE
  WHEN ?3 IS NULL THEN -1
  ELSE ?3
END
`

type ListSleepEntriesParams struct {
	FromRecordedAt interface{}
	ToRecordedAt   interface{}
	LimitCount     interface{}
}

func (q *Queries) ListSleepEntries(ctx context.Context, arg ListSleepEntriesParams) ([]HealthSleepEntry, error) {
	rows, err := q.db.QueryContext(ctx, listSleepEntries, arg.FromRecordedAt, arg.ToRecordedAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthSleepEntry
	for rows.Next() {
		var i HealthSleepEntry
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.QualityScore,
			&i.WakeupCount,
			&i.Note,
			&i.Source,
			&i.SourceRecordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeightEntries = `-- name: ListWeightEntries :many
SELECT
  id,
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at,
  deleted_at
FROM health_weight_entry
WHERE deleted_at IS NULL
  AND (?1 IS NULL OR recorded_at >= ?1)
  AND (?2 IS NULL OR recorded_at <= ?2)
ORDER BY recorded_at DESC, id DESC
LIMIT CASE
  WHEN ?3 IS NULL THEN -1
  ELSE ?3
END
`

type ListWeightEntriesParams struct {
	FromRecordedAt interface{}
	ToRecordedAt   interface{}
	LimitCount     interface{}
}

func (q *Queries) ListWeightEntries(ctx context.Context, arg ListWeightEntriesParams) ([]HealthWeightEntry, error) {
	rows, err := q.db.QueryContext(ctx, listWeightEntries, arg.FromRecordedAt, arg.ToRecordedAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthWeightEntry
	for rows.Next() {
		var i HealthWeightEntry
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.Value,
			&i.Unit,
			&i.Source,
			&i.SourceRecordHash,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBloodPressureEntry = `-- name: UpdateBloodPressureEntry :one
UPDATE health_blood_pressure_entry
SET
  recorded_at = ?1,
  systolic = ?2,
  diastolic = ?3,
  pulse = ?4,
  note = ?5,
  updated_at = ?6
WHERE id = ?7
  AND deleted_at IS NULL
RETURNING
  id,
  recorded_at,
  systolic,
  diastolic,
  pulse,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type UpdateBloodPressureEntryParams struct {
	RecordedAt string
	Systolic   int64
	Diastolic  int64
	Pulse      *int64
	Note       *string
	UpdatedAt  string
	ID         int64
}

type UpdateBloodPressureEntryRow struct {
	ID               int64
	RecordedAt       string
	Systolic         int64
	Diastolic        int64
	Pulse            *int64
	Note             *string
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
}

func (q *Queries) UpdateBloodPressureEntry(ctx context.Context, arg UpdateBloodPressureEntryParams) (UpdateBloodPressureEntryRow, error) {
	row := q.db.QueryRowContext(ctx, updateBloodPressureEntry,
		arg.RecordedAt,
		arg.Systolic,
		arg.Diastolic,
		arg.Pulse,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UpdateBloodPressureEntryRow
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Systolic,
		&i.Diastolic,
		&i.Pulse,
		&i.Note,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBodyCompositionEntry = `-- name: UpdateBodyCompositionEntry :one
UPDATE health_body_composition_entry
SET
  recorded_at = ?1,
  body_fat_percent = ?2,
  weight_value = ?3,
  weight_unit = ?4,
  method = ?5,
  note = ?6,
  updated_at = ?7
WHERE id = ?8
  AND deleted_at IS NULL
RETURNING
  id,
  recorded_at,
  body_fat_percent,
  weight_value,
  weight_unit,
  method,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type UpdateBodyCompositionEntryParams struct {
	RecordedAt     string
	BodyFatPercent *float64
	WeightValue    *float64
	WeightUnit     *string
	Method         *string
	Note           *string
	UpdatedAt      string
	ID             int64
}

func (q *Queries) UpdateBodyCompositionEntry(ctx context.Context, arg UpdateBodyCompositionEntryParams) (HealthBodyCompositionEntry, error) {
	row := q.db.QueryRowContext(ctx, updateBodyCompositionEntry,
		arg.RecordedAt,
		arg.BodyFatPercent,
		arg.WeightValue,
		arg.WeightUnit,
		arg.Method,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	var i HealthBodyCompositionEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.BodyFatPercent,
		&i.WeightValue,
		&i.WeightUnit,
		&i.Method,
		&i.Note,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateImagingRecord = `-- name: UpdateImagingRecord :one
UPDATE health_imaging_record
SET
  performed_at = ?1,
  modality = ?2,
  body_site = ?3,
  title = ?4,
  summary = ?5,
  impression = ?6,
  note = ?7,
  updated_at = ?8
WHERE id = ?9
  AND deleted_at IS NULL
RETURNING
  id,
  performed_at,
  modality,
  body_site,
  title,
  summary,
  impression,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type UpdateImagingRecordParams struct {
	PerformedAt string
	Modality    string
	BodySite    *string
	Title       *string
	Summary     string
	Impression  *string
	Note        *string
	UpdatedAt   string
	ID          int64
}

func (q *Queries) UpdateImagingRecord(ctx context.Context, arg UpdateImagingRecordParams) (HealthImagingRecord, error) {
	row := q.db.QueryRowContext(ctx, updateImagingRecord,
		arg.PerformedAt,
		arg.Modality,
		arg.BodySite,
		arg.Title,
		arg.Summary,
		arg.Impression,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	var i HealthImagingRecord
	err := row.Scan(
		&i.ID,
		&i.PerformedAt,
		&i.Modality,
		&i.BodySite,
		&i.Title,
		&i.Summary,
		&i.Impression,
		&i.Note,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLabCollection = `-- name: UpdateLabCollection :one
UPDATE health_lab_collection
SET
  collected_at = ?1,
  note = ?2,
  updated_at = ?3
WHERE id = ?4
  AND deleted_at IS NULL
RETURNING
  id,
  collected_at,
  note,
  source,
  created_at,
  updated_at,
  deleted_at
`

type UpdateLabCollectionParams struct {
	CollectedAt string
	Note        *string
	UpdatedAt   *string
	ID          int64
}

type UpdateLabCollectionRow struct {
	ID          int64
	CollectedAt string
	Note        *string
	Source      string
	CreatedAt   string
	UpdatedAt   *string
	DeletedAt   *string
}

func (q *Queries) UpdateLabCollection(ctx context.Context, arg UpdateLabCollectionParams) (UpdateLabCollectionRow, error) {
	row := q.db.QueryRowContext(ctx, updateLabCollection,
		arg.CollectedAt,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UpdateLabCollectionRow
	err := row.Scan(
		&i.ID,
		&i.CollectedAt,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMedicationCourse = `-- name: UpdateMedicationCourse :one
UPDATE health_medication_course
SET
  name = ?1,
  dosage_text = ?2,
  start_date = ?3,
  end_date = ?4,
  note = ?5,
  updated_at = ?6
WHERE id = ?7
  AND deleted_at IS NULL
RETURNING
  id,
  name,
  dosage_text,
  start_date,
  end_date,
  note,
  source,
  created_at,
  updated_at,
  deleted_at
`

type UpdateMedicationCourseParams struct {
	Name       string
	DosageText *string
	StartDate  string
	EndDate    *string
	Note       *string
	UpdatedAt  string
	ID         int64
}

type UpdateMedicationCourseRow struct {
	ID         int64
	Name       string
	DosageText *string
	StartDate  string
	EndDate    *string
	Note       *string
	Source     string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  *string
}

func (q *Queries) UpdateMedicationCourse(ctx context.Context, arg UpdateMedicationCourseParams) (UpdateMedicationCourseRow, error) {
	row := q.db.QueryRowContext(ctx, updateMedicationCourse,
		arg.Name,
		arg.DosageText,
		arg.StartDate,
		arg.EndDate,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	var i UpdateMedicationCourseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DosageText,
		&i.StartDate,
		&i.EndDate,
		&i.Note,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSleepEntry = `-- name: UpdateSleepEntry :one
UPDATE health_sleep_entry
SET
  recorded_at = COALESCE(?1, recorded_at),
  quality_score = COALESCE(?2, quality_score),
  wakeup_count = COALESCE(?3, wakeup_count),
  note = COALESCE(?4, note),
  updated_at = ?5
WHERE id = ?6
  AND deleted_at IS NULL
RETURNING
  id,
  recorded_at,
  quality_score,
  wakeup_count,
  note,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type UpdateSleepEntryParams struct {
	RecordedAt   *string
	QualityScore *int64
	WakeupCount  *int64
	Note         *string
	UpdatedAt    string
	ID           int64
}

func (q *Queries) UpdateSleepEntry(ctx context.Context, arg UpdateSleepEntryParams) (HealthSleepEntry, error) {
	row := q.db.QueryRowContext(ctx, updateSleepEntry,
		arg.RecordedAt,
		arg.QualityScore,
		arg.WakeupCount,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	var i HealthSleepEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.QualityScore,
		&i.WakeupCount,
		&i.Note,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWeightEntry = `-- name: UpdateWeightEntry :one
UPDATE health_weight_entry
SET
  recorded_at = COALESCE(?1, recorded_at),
  value = COALESCE(?2, value),
  unit = COALESCE(?3, unit),
  note = COALESCE(?4, note),
  updated_at = ?5
WHERE id = ?6
  AND deleted_at IS NULL
RETURNING
  id,
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at,
  deleted_at
`

type UpdateWeightEntryParams struct {
	RecordedAt *string
	Value      *float64
	Unit       *string
	Note       *string
	UpdatedAt  string
	ID         int64
}

func (q *Queries) UpdateWeightEntry(ctx context.Context, arg UpdateWeightEntryParams) (HealthWeightEntry, error) {
	row := q.db.QueryRowContext(ctx, updateWeightEntry,
		arg.RecordedAt,
		arg.Value,
		arg.Unit,
		arg.Note,
		arg.UpdatedAt,
		arg.ID,
	)
	var i HealthWeightEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Value,
		&i.Unit,
		&i.Source,
		&i.SourceRecordHash,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
