// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package sqlc

import (
	"context"
)

const countActiveMedicationCourses = `-- name: CountActiveMedicationCourses :one
SELECT COUNT(*) AS count
FROM health_medication_course
WHERE deleted_at IS NULL
  AND (end_date IS NULL OR end_date >= ?1)
`

func (q *Queries) CountActiveMedicationCourses(ctx context.Context, today *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveMedicationCourses, today)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBloodPressureEntry = `-- name: CreateBloodPressureEntry :one
INSERT INTO health_blood_pressure_entry (
  recorded_at,
  systolic,
  diastolic,
  pulse,
  source,
  source_record_hash,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING
  id,
  recorded_at,
  systolic,
  diastolic,
  pulse,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type CreateBloodPressureEntryParams struct {
	RecordedAt       string
	Systolic         int64
	Diastolic        int64
	Pulse            *int64
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateBloodPressureEntry(ctx context.Context, arg CreateBloodPressureEntryParams) (HealthBloodPressureEntry, error) {
	row := q.db.QueryRowContext(ctx, createBloodPressureEntry,
		arg.RecordedAt,
		arg.Systolic,
		arg.Diastolic,
		arg.Pulse,
		arg.Source,
		arg.SourceRecordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i HealthBloodPressureEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Systolic,
		&i.Diastolic,
		&i.Pulse,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLabCollection = `-- name: CreateLabCollection :one
INSERT INTO health_lab_collection (
  collected_at,
  source,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4
)
RETURNING
  id,
  collected_at,
  source,
  created_at,
  updated_at,
  deleted_at
`

type CreateLabCollectionParams struct {
	CollectedAt string
	Source      string
	CreatedAt   string
	UpdatedAt   *string
}

func (q *Queries) CreateLabCollection(ctx context.Context, arg CreateLabCollectionParams) (HealthLabCollection, error) {
	row := q.db.QueryRowContext(ctx, createLabCollection,
		arg.CollectedAt,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i HealthLabCollection
	err := row.Scan(
		&i.ID,
		&i.CollectedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLabPanel = `-- name: CreateLabPanel :one
INSERT INTO health_lab_panel (
  collection_id,
  panel_name,
  display_order
) VALUES (
  ?1,
  ?2,
  ?3
)
RETURNING
  id,
  collection_id,
  panel_name,
  display_order
`

type CreateLabPanelParams struct {
	CollectionID int64
	PanelName    string
	DisplayOrder int64
}

func (q *Queries) CreateLabPanel(ctx context.Context, arg CreateLabPanelParams) (HealthLabPanel, error) {
	row := q.db.QueryRowContext(ctx, createLabPanel, arg.CollectionID, arg.PanelName, arg.DisplayOrder)
	var i HealthLabPanel
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.PanelName,
		&i.DisplayOrder,
	)
	return i, err
}

const createLabResult = `-- name: CreateLabResult :one
INSERT INTO health_lab_result (
  panel_id,
  test_name,
  canonical_slug,
  value_text,
  value_numeric,
  units,
  range_text,
  flag,
  display_order
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8,
  ?9
)
RETURNING
  id,
  panel_id,
  test_name,
  canonical_slug,
  value_text,
  value_numeric,
  units,
  range_text,
  flag,
  display_order
`

type CreateLabResultParams struct {
	PanelID       int64
	TestName      string
	CanonicalSlug *string
	ValueText     string
	ValueNumeric  *float64
	Units         *string
	RangeText     *string
	Flag          *string
	DisplayOrder  int64
}

func (q *Queries) CreateLabResult(ctx context.Context, arg CreateLabResultParams) (HealthLabResult, error) {
	row := q.db.QueryRowContext(ctx, createLabResult,
		arg.PanelID,
		arg.TestName,
		arg.CanonicalSlug,
		arg.ValueText,
		arg.ValueNumeric,
		arg.Units,
		arg.RangeText,
		arg.Flag,
		arg.DisplayOrder,
	)
	var i HealthLabResult
	err := row.Scan(
		&i.ID,
		&i.PanelID,
		&i.TestName,
		&i.CanonicalSlug,
		&i.ValueText,
		&i.ValueNumeric,
		&i.Units,
		&i.RangeText,
		&i.Flag,
		&i.DisplayOrder,
	)
	return i, err
}

const createMedicationCourse = `-- name: CreateMedicationCourse :one
INSERT INTO health_medication_course (
  name,
  dosage_text,
  start_date,
  end_date,
  source,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
)
RETURNING
  id,
  name,
  dosage_text,
  start_date,
  end_date,
  source,
  created_at,
  updated_at,
  deleted_at
`

type CreateMedicationCourseParams struct {
	Name       string
	DosageText *string
	StartDate  string
	EndDate    *string
	Source     string
	CreatedAt  string
	UpdatedAt  string
}

func (q *Queries) CreateMedicationCourse(ctx context.Context, arg CreateMedicationCourseParams) (HealthMedicationCourse, error) {
	row := q.db.QueryRowContext(ctx, createMedicationCourse,
		arg.Name,
		arg.DosageText,
		arg.StartDate,
		arg.EndDate,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i HealthMedicationCourse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DosageText,
		&i.StartDate,
		&i.EndDate,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createWeightEntry = `-- name: CreateWeightEntry :one
INSERT INTO health_weight_entry (
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7,
  ?8
)
RETURNING
  id,
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at,
  deleted_at
`

type CreateWeightEntryParams struct {
	RecordedAt       string
	Value            float64
	Unit             string
	Source           string
	SourceRecordHash string
	Note             *string
	CreatedAt        string
	UpdatedAt        string
}

func (q *Queries) CreateWeightEntry(ctx context.Context, arg CreateWeightEntryParams) (HealthWeightEntry, error) {
	row := q.db.QueryRowContext(ctx, createWeightEntry,
		arg.RecordedAt,
		arg.Value,
		arg.Unit,
		arg.Source,
		arg.SourceRecordHash,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i HealthWeightEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Value,
		&i.Unit,
		&i.Source,
		&i.SourceRecordHash,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteBloodPressureEntry = `-- name: DeleteBloodPressureEntry :one
UPDATE health_blood_pressure_entry
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteBloodPressureEntryParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) DeleteBloodPressureEntry(ctx context.Context, arg DeleteBloodPressureEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteBloodPressureEntry, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteLabCollection = `-- name: DeleteLabCollection :one
UPDATE health_lab_collection
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteLabCollectionParams struct {
	DeletedAt *string
	UpdatedAt *string
	ID        int64
}

func (q *Queries) DeleteLabCollection(ctx context.Context, arg DeleteLabCollectionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteLabCollection, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteLabPanelsByCollection = `-- name: DeleteLabPanelsByCollection :exec
DELETE FROM health_lab_panel
WHERE collection_id = ?1
`

func (q *Queries) DeleteLabPanelsByCollection(ctx context.Context, collectionID int64) error {
	_, err := q.db.ExecContext(ctx, deleteLabPanelsByCollection, collectionID)
	return err
}

const deleteMedicationCourse = `-- name: DeleteMedicationCourse :one
UPDATE health_medication_course
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteMedicationCourseParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) DeleteMedicationCourse(ctx context.Context, arg DeleteMedicationCourseParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteMedicationCourse, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteWeightEntry = `-- name: DeleteWeightEntry :one
UPDATE health_weight_entry
SET
  deleted_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING id
`

type DeleteWeightEntryParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        int64
}

func (q *Queries) DeleteWeightEntry(ctx context.Context, arg DeleteWeightEntryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, deleteWeightEntry, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findManualWeightEntry = `-- name: FindManualWeightEntry :one
SELECT
  id,
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at,
  deleted_at
FROM health_weight_entry
WHERE deleted_at IS NULL
  AND source = 'manual'
  AND substr(recorded_at, 1, 10) = ?1
  AND unit = ?2
ORDER BY id DESC
LIMIT 1
`

type FindManualWeightEntryParams struct {
	RecordedDate string
	Unit         string
}

func (q *Queries) FindManualWeightEntry(ctx context.Context, arg FindManualWeightEntryParams) (HealthWeightEntry, error) {
	row := q.db.QueryRowContext(ctx, findManualWeightEntry, arg.RecordedDate, arg.Unit)
	var i HealthWeightEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Value,
		&i.Unit,
		&i.Source,
		&i.SourceRecordHash,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLabCollection = `-- name: GetLabCollection :one
SELECT
  id,
  collected_at,
  source,
  created_at,
  updated_at,
  deleted_at
FROM health_lab_collection
WHERE id = ?1
  AND deleted_at IS NULL
`

func (q *Queries) GetLabCollection(ctx context.Context, id int64) (HealthLabCollection, error) {
	row := q.db.QueryRowContext(ctx, getLabCollection, id)
	var i HealthLabCollection
	err := row.Scan(
		&i.ID,
		&i.CollectedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveMedicationCourses = `-- name: ListActiveMedicationCourses :many
SELECT
  id,
  name,
  dosage_text,
  start_date,
  end_date,
  source,
  created_at,
  updated_at,
  deleted_at
FROM health_medication_course
WHERE deleted_at IS NULL
  AND (end_date IS NULL OR end_date >= ?1)
ORDER BY start_date DESC, id DESC
`

func (q *Queries) ListActiveMedicationCourses(ctx context.Context, today *string) ([]HealthMedicationCourse, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMedicationCourses, today)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthMedicationCourse
	for rows.Next() {
		var i HealthMedicationCourse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DosageText,
			&i.StartDate,
			&i.EndDate,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBloodPressureEntries = `-- name: ListBloodPressureEntries :many
SELECT
  id,
  recorded_at,
  systolic,
  diastolic,
  pulse,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
FROM health_blood_pressure_entry
WHERE deleted_at IS NULL
  AND (?1 IS NULL OR recorded_at >= ?1)
  AND (?2 IS NULL OR recorded_at <= ?2)
ORDER BY recorded_at DESC, id DESC
LIMIT CASE
  WHEN ?3 IS NULL THEN -1
  ELSE ?3
END
`

type ListBloodPressureEntriesParams struct {
	FromRecordedAt interface{}
	ToRecordedAt   interface{}
	LimitCount     interface{}
}

func (q *Queries) ListBloodPressureEntries(ctx context.Context, arg ListBloodPressureEntriesParams) ([]HealthBloodPressureEntry, error) {
	rows, err := q.db.QueryContext(ctx, listBloodPressureEntries, arg.FromRecordedAt, arg.ToRecordedAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthBloodPressureEntry
	for rows.Next() {
		var i HealthBloodPressureEntry
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.Systolic,
			&i.Diastolic,
			&i.Pulse,
			&i.Source,
			&i.SourceRecordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabCollections = `-- name: ListLabCollections :many
SELECT
  id,
  collected_at,
  source,
  created_at,
  updated_at,
  deleted_at
FROM health_lab_collection
WHERE deleted_at IS NULL
ORDER BY collected_at DESC, id DESC
`

func (q *Queries) ListLabCollections(ctx context.Context) ([]HealthLabCollection, error) {
	rows, err := q.db.QueryContext(ctx, listLabCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthLabCollection
	for rows.Next() {
		var i HealthLabCollection
		if err := rows.Scan(
			&i.ID,
			&i.CollectedAt,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabPanels = `-- name: ListLabPanels :many
SELECT
  id,
  collection_id,
  panel_name,
  display_order
FROM health_lab_panel
ORDER BY collection_id ASC, display_order ASC, id ASC
`

func (q *Queries) ListLabPanels(ctx context.Context) ([]HealthLabPanel, error) {
	rows, err := q.db.QueryContext(ctx, listLabPanels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthLabPanel
	for rows.Next() {
		var i HealthLabPanel
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.PanelName,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabResults = `-- name: ListLabResults :many
SELECT
  id,
  panel_id,
  test_name,
  canonical_slug,
  value_text,
  value_numeric,
  units,
  range_text,
  flag,
  display_order
FROM health_lab_result
ORDER BY panel_id ASC, display_order ASC, id ASC
`

func (q *Queries) ListLabResults(ctx context.Context) ([]HealthLabResult, error) {
	rows, err := q.db.QueryContext(ctx, listLabResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthLabResult
	for rows.Next() {
		var i HealthLabResult
		if err := rows.Scan(
			&i.ID,
			&i.PanelID,
			&i.TestName,
			&i.CanonicalSlug,
			&i.ValueText,
			&i.ValueNumeric,
			&i.Units,
			&i.RangeText,
			&i.Flag,
			&i.DisplayOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLabResultsWithCollection = `-- name: ListLabResultsWithCollection :many
SELECT
  health_lab_result.id,
  health_lab_result.panel_id,
  health_lab_result.test_name,
  health_lab_result.canonical_slug,
  health_lab_result.value_text,
  health_lab_result.value_numeric,
  health_lab_result.units,
  health_lab_result.range_text,
  health_lab_result.flag,
  health_lab_result.display_order,
  health_lab_collection.collected_at,
  health_lab_collection.id AS collection_id,
  health_lab_panel.panel_name
FROM health_lab_result
INNER JOIN health_lab_panel ON health_lab_panel.id = health_lab_result.panel_id
INNER JOIN health_lab_collection ON health_lab_collection.id = health_lab_panel.collection_id
WHERE health_lab_result.canonical_slug IS NOT NULL
  AND health_lab_collection.deleted_at IS NULL
ORDER BY health_lab_collection.collected_at DESC, health_lab_result.id DESC
`

type ListLabResultsWithCollectionRow struct {
	ID            int64
	PanelID       int64
	TestName      string
	CanonicalSlug *string
	ValueText     string
	ValueNumeric  *float64
	Units         *string
	RangeText     *string
	Flag          *string
	DisplayOrder  int64
	CollectedAt   string
	CollectionID  int64
	PanelName     string
}

func (q *Queries) ListLabResultsWithCollection(ctx context.Context) ([]ListLabResultsWithCollectionRow, error) {
	rows, err := q.db.QueryContext(ctx, listLabResultsWithCollection)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLabResultsWithCollectionRow
	for rows.Next() {
		var i ListLabResultsWithCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.PanelID,
			&i.TestName,
			&i.CanonicalSlug,
			&i.ValueText,
			&i.ValueNumeric,
			&i.Units,
			&i.RangeText,
			&i.Flag,
			&i.DisplayOrder,
			&i.CollectedAt,
			&i.CollectionID,
			&i.PanelName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationCourses = `-- name: ListMedicationCourses :many
SELECT
  id,
  name,
  dosage_text,
  start_date,
  end_date,
  source,
  created_at,
  updated_at,
  deleted_at
FROM health_medication_course
WHERE deleted_at IS NULL
ORDER BY start_date DESC, id DESC
`

func (q *Queries) ListMedicationCourses(ctx context.Context) ([]HealthMedicationCourse, error) {
	rows, err := q.db.QueryContext(ctx, listMedicationCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthMedicationCourse
	for rows.Next() {
		var i HealthMedicationCourse
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DosageText,
			&i.StartDate,
			&i.EndDate,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeightEntries = `-- name: ListWeightEntries :many
SELECT
  id,
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at,
  deleted_at
FROM health_weight_entry
WHERE deleted_at IS NULL
  AND (?1 IS NULL OR recorded_at >= ?1)
  AND (?2 IS NULL OR recorded_at <= ?2)
ORDER BY recorded_at DESC, id DESC
LIMIT CASE
  WHEN ?3 IS NULL THEN -1
  ELSE ?3
END
`

type ListWeightEntriesParams struct {
	FromRecordedAt interface{}
	ToRecordedAt   interface{}
	LimitCount     interface{}
}

func (q *Queries) ListWeightEntries(ctx context.Context, arg ListWeightEntriesParams) ([]HealthWeightEntry, error) {
	rows, err := q.db.QueryContext(ctx, listWeightEntries, arg.FromRecordedAt, arg.ToRecordedAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HealthWeightEntry
	for rows.Next() {
		var i HealthWeightEntry
		if err := rows.Scan(
			&i.ID,
			&i.RecordedAt,
			&i.Value,
			&i.Unit,
			&i.Source,
			&i.SourceRecordHash,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBloodPressureEntry = `-- name: UpdateBloodPressureEntry :one
UPDATE health_blood_pressure_entry
SET
  recorded_at = ?1,
  systolic = ?2,
  diastolic = ?3,
  pulse = ?4,
  updated_at = ?5
WHERE id = ?6
  AND deleted_at IS NULL
RETURNING
  id,
  recorded_at,
  systolic,
  diastolic,
  pulse,
  source,
  source_record_hash,
  created_at,
  updated_at,
  deleted_at
`

type UpdateBloodPressureEntryParams struct {
	RecordedAt string
	Systolic   int64
	Diastolic  int64
	Pulse      *int64
	UpdatedAt  string
	ID         int64
}

func (q *Queries) UpdateBloodPressureEntry(ctx context.Context, arg UpdateBloodPressureEntryParams) (HealthBloodPressureEntry, error) {
	row := q.db.QueryRowContext(ctx, updateBloodPressureEntry,
		arg.RecordedAt,
		arg.Systolic,
		arg.Diastolic,
		arg.Pulse,
		arg.UpdatedAt,
		arg.ID,
	)
	var i HealthBloodPressureEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Systolic,
		&i.Diastolic,
		&i.Pulse,
		&i.Source,
		&i.SourceRecordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLabCollection = `-- name: UpdateLabCollection :one
UPDATE health_lab_collection
SET
  collected_at = ?1,
  updated_at = ?2
WHERE id = ?3
  AND deleted_at IS NULL
RETURNING
  id,
  collected_at,
  source,
  created_at,
  updated_at,
  deleted_at
`

type UpdateLabCollectionParams struct {
	CollectedAt string
	UpdatedAt   *string
	ID          int64
}

func (q *Queries) UpdateLabCollection(ctx context.Context, arg UpdateLabCollectionParams) (HealthLabCollection, error) {
	row := q.db.QueryRowContext(ctx, updateLabCollection, arg.CollectedAt, arg.UpdatedAt, arg.ID)
	var i HealthLabCollection
	err := row.Scan(
		&i.ID,
		&i.CollectedAt,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMedicationCourse = `-- name: UpdateMedicationCourse :one
UPDATE health_medication_course
SET
  name = ?1,
  dosage_text = ?2,
  start_date = ?3,
  end_date = ?4,
  updated_at = ?5
WHERE id = ?6
  AND deleted_at IS NULL
RETURNING
  id,
  name,
  dosage_text,
  start_date,
  end_date,
  source,
  created_at,
  updated_at,
  deleted_at
`

type UpdateMedicationCourseParams struct {
	Name       string
	DosageText *string
	StartDate  string
	EndDate    *string
	UpdatedAt  string
	ID         int64
}

func (q *Queries) UpdateMedicationCourse(ctx context.Context, arg UpdateMedicationCourseParams) (HealthMedicationCourse, error) {
	row := q.db.QueryRowContext(ctx, updateMedicationCourse,
		arg.Name,
		arg.DosageText,
		arg.StartDate,
		arg.EndDate,
		arg.UpdatedAt,
		arg.ID,
	)
	var i HealthMedicationCourse
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DosageText,
		&i.StartDate,
		&i.EndDate,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateWeightEntry = `-- name: UpdateWeightEntry :one
UPDATE health_weight_entry
SET
  recorded_at = COALESCE(?1, recorded_at),
  value = COALESCE(?2, value),
  unit = COALESCE(?3, unit),
  updated_at = ?4
WHERE id = ?5
  AND deleted_at IS NULL
RETURNING
  id,
  recorded_at,
  value,
  unit,
  source,
  source_record_hash,
  note,
  created_at,
  updated_at,
  deleted_at
`

type UpdateWeightEntryParams struct {
	RecordedAt *string
	Value      *float64
	Unit       *string
	UpdatedAt  string
	ID         int64
}

func (q *Queries) UpdateWeightEntry(ctx context.Context, arg UpdateWeightEntryParams) (HealthWeightEntry, error) {
	row := q.db.QueryRowContext(ctx, updateWeightEntry,
		arg.RecordedAt,
		arg.Value,
		arg.Unit,
		arg.UpdatedAt,
		arg.ID,
	)
	var i HealthWeightEntry
	err := row.Scan(
		&i.ID,
		&i.RecordedAt,
		&i.Value,
		&i.Unit,
		&i.Source,
		&i.SourceRecordHash,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
