// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type HealthBloodPressureEntry struct {
	ID               int64
	RecordedAt       string
	Systolic         int64
	Diastolic        int64
	Pulse            *int64
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
}

type HealthBodyCompositionEntry struct {
	ID               int64
	RecordedAt       string
	BodyFatPercent   *float64
	WeightValue      *float64
	WeightUnit       *string
	Method           *string
	Note             *string
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
}

type HealthImagingRecord struct {
	ID               int64
	PerformedAt      string
	Modality         string
	BodySite         *string
	Title            *string
	Summary          string
	Impression       *string
	Note             *string
	Source           string
	SourceRecordHash string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
}

type HealthLabCollection struct {
	ID          int64
	CollectedAt string
	Source      string
	CreatedAt   string
	UpdatedAt   *string
	DeletedAt   *string
	Note        *string
}

type HealthLabPanel struct {
	ID           int64
	CollectionID int64
	PanelName    string
	DisplayOrder int64
}

type HealthLabResult struct {
	ID            int64
	PanelID       int64
	TestName      string
	CanonicalSlug *string
	ValueText     string
	ValueNumeric  *float64
	Units         *string
	RangeText     *string
	Flag          *string
	DisplayOrder  int64
}

type HealthMedicationCourse struct {
	ID         int64
	Name       string
	DosageText *string
	StartDate  string
	EndDate    *string
	Source     string
	CreatedAt  string
	UpdatedAt  string
	DeletedAt  *string
	Note       *string
}

type HealthWeightEntry struct {
	ID               int64
	RecordedAt       string
	Value            float64
	Unit             string
	Source           string
	SourceRecordHash string
	Note             *string
	CreatedAt        string
	UpdatedAt        string
	DeletedAt        *string
}
